<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
        //resolve, reject, all, race
        //resolve == then, reject == error
        // let promise = new Promise(function(resolve, reject) {
        //    reject(111);
        // })
        // promise.then(response => {
        //    console.log('成功')
        // }).catch(error =>{
        //    console.log('失败', error)
        // })

        //链式
        function promise1(status) {
            return new Promise(function(resolve, reject) {
                if (status) {
                    resolve('promise1成功');
                } else {
                    reject('promise1失败');
                }
               
            });
        }
        promise1(true).then(response =>{
            console.log(response);
        }).catch(error =>{
            console.log(error);
        });

        //链式
        function promise2(status) {
            return new Promise(function(resolve, reject) {
                if (status) {
                    resolve('promise2成功');
                } else {
                    reject('promise2失败');
                }
               
            });
        }
        promise1(true).then(response =>{
            console.log(response);
            return promise2(true);
        }).then(response =>{
            console.log(response);
        }).catch(error =>{
            console.log(error);
        }) 
        
        //all方法，数组内的promise全部成功才会执行then回调，只有有一个不成功就会catch
        // Promise.all([promise1(true), promise2(false)]).then(function(){
        //     console.log('全部调用成功');
        // }).catch(error =>{
        //     console.log('有些可能失败了');
        // })

        //只有一个是返回resolve，就代表成功，就会回调then,但是只有第一个返回reject，那么就失败
        Promise.race([promise1(true), promise2(false)]).then(function(){
            console.log('有成功就会进来');
        }).catch(error =>{
            console.log('有些可能失败了');
        })
    </script>
</body>
</html>